### PR TITLE
Allow React 16.x as a peerDependency

### PR DESCRIPTION
**Pull request by ubnt-marc-khouri**

### CODE REVIEW

**Comment by zeroasterisk** [comment]
Thanks!

**Comment by zeroasterisk** [comment]
Can you rebase and push? It should happen without a conflict.

**Comment by zeroasterisk** [comment]
I resolved and merged, thanks

**Comment by ubnt-marc-khouri** [comment]
sorry, totally missed your request to rebase -- thanks for the merge! :)

**Pull request merged**
